# Generated by Django 4.2.2 on 2023-06-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p1',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='p2',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='p3',
            name='p3',
        ),
        migrations.AddField(
            model_name='p1',
            name='p1_fim',
            field=models.CharField(blank='true', max_length=10, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='p1',
            name='p1_inicio',
            field=models.CharField(blank='true', max_length=10, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='p2',
            name='p2_fim',
            field=models.CharField(blank='true', max_length=10, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='p2',
            name='p2_inicio',
            field=models.CharField(blank='true', max_length=10, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='p3',
            name='p3_fim',
            field=models.CharField(blank='true', max_length=10, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='p3',
            name='p3_inicio',
            field=models.CharField(blank='true', max_length=10, null='true'),
            preserve_default='true',
        ),
        migrations.AlterField(
            model_name='contador',
            name='contador',
            field=models.CharField(blank='true', max_length=100, null='true'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='data',
            field=models.CharField(blank='true', max_length=100, null='true'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='data',
            field=models.CharField(blank='true', max_length=100, null='true'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='pergunta',
            field=models.CharField(blank='true', max_length=250, null='true'),
        ),
    ]
