# Generated by Django 4.2.2 on 2023-06-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0002_remove_p1_p1_remove_p2_p2_remove_p3_p3_p1_p1_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nPessoa', models.CharField(blank='true', max_length=250, null='true')),
                ('descricao', models.CharField(blank='true', max_length=100, null='true')),
                ('total', models.CharField(blank='true', max_length=10, null='true')),
                ('data', models.CharField(blank='true', max_length=100, null='true')),
            ],
        ),
    ]
