# Generated by Django 4.2.2 on 2023-07-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0003_compras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contador',
            name='data',
            field=models.DateTimeField(blank='true', null='true'),
        ),
    ]
