# Generated by Django 4.2.2 on 2023-07-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0005_alter_contador_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contador',
            name='turno',
            field=models.CharField(blank='true', max_length=10, null='true'),
            preserve_default='true',
        ),
    ]
